app:
    resource: "@AppBundle/Controller/"
    type:     annotation
_welcome:
  path:      /
  defaults:  { _controller: AppBundle:Main:homepage }
hello:
  path: /hello/{name}
  defaults: { _controller: AppBundle:Default:hello }